# Generated by Django 6.0.3 on 2026-04-08 23:46

import django.db.models.deletion
from django.db import migrations, models


def ensure_service_base_tables(apps, schema_editor):
    existing_tables = set(schema_editor.connection.introspection.table_names())

    OwnerUser = apps.get_model("service", "OwnerUser")
    Member = apps.get_model("service", "Member")
    Comment = apps.get_model("service", "Comment")

    if OwnerUser._meta.db_table not in existing_tables:
        schema_editor.create_model(OwnerUser)
        existing_tables.add(OwnerUser._meta.db_table)

    if Member._meta.db_table not in existing_tables:
        schema_editor.create_model(Member)
        existing_tables.add(Member._meta.db_table)

    if Comment._meta.db_table not in existing_tables:
        schema_editor.create_model(Comment)
        existing_tables.add(Comment._meta.db_table)


def ensure_comment_columns_and_reply_table(apps, schema_editor):
    Comment = apps.get_model("service", "Comment")
    Member = apps.get_model("service", "Member")
    comment_table = Comment._meta.db_table
    reply_table = "comment_replies"

    existing_columns = {
        column.name for column in schema_editor.connection.introspection.get_table_description(
            schema_editor.connection.cursor(), comment_table
        )
    }

    column_specs = [
        (
            "dislikes",
            models.IntegerField(default=0),
        ),
        (
            "likes",
            models.IntegerField(default=0),
        ),
        (
            "rating",
            models.IntegerField(choices=[(1, "1"), (2, "2"), (3, "3"), (4, "4"), (5, "5")], default=5),
        ),
    ]
    for column_name, field in column_specs:
        if column_name in existing_columns:
            continue
        field.set_attributes_from_name(column_name)
        schema_editor.add_field(Comment, field)

    existing_tables = set(schema_editor.connection.introspection.table_names())
    if reply_table in existing_tables:
        return

    with schema_editor.connection.cursor() as cursor:
        cursor.execute(
            f"""
            CREATE TABLE {reply_table} (
                id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                content text NOT NULL,
                created_at timestamp with time zone NOT NULL,
                comment_id bigint NOT NULL REFERENCES {comment_table}(id) DEFERRABLE INITIALLY DEFERRED,
                member_id bigint NOT NULL REFERENCES {Member._meta.db_table}(id) DEFERRABLE INITIALLY DEFERRED
            )
            """
        )
        cursor.execute(
            f"CREATE INDEX {reply_table}_comment_id_idx ON {reply_table} (comment_id)"
        )
        cursor.execute(
            f"CREATE INDEX {reply_table}_member_id_idx ON {reply_table} (member_id)"
        )


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(ensure_service_base_tables, migrations.RunPython.noop),
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunPython(ensure_comment_columns_and_reply_table, migrations.RunPython.noop),
            ],
            state_operations=[
                migrations.AddField(
                    model_name='comment',
                    name='dislikes',
                    field=models.IntegerField(default=0),
                ),
                migrations.AddField(
                    model_name='comment',
                    name='likes',
                    field=models.IntegerField(default=0),
                ),
                migrations.AddField(
                    model_name='comment',
                    name='rating',
                    field=models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], default=5),
                ),
                migrations.CreateModel(
                    name='Reply',
                    fields=[
                        ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                        ('content', models.TextField()),
                        ('created_at', models.DateTimeField(auto_now_add=True)),
                        ('comment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='service.comment')),
                        ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='service.member')),
                    ],
                    options={
                        'db_table': 'comment_replies',
                        'ordering': ['created_at'],
                    },
                ),
            ],
        ),
    ]
