# Generated by Django 6.0.3 on 2026-03-26 16:39

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CountdownCard',
            fields=[
                ('id', models.CharField(default=core.models.generate_uuid, max_length=36, primary_key=True, serialize=False)),
                ('title', models.TextField()),
                ('description', models.TextField()),
                ('file_url', models.TextField()),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('status', models.CharField(choices=[('active', 'Active'), ('cancelled', 'Cancelled'), ('completed', 'Completed')], default='active', max_length=20)),
                ('created_by', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('version', models.IntegerField(default=1)),
                ('is_published', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name_plural': 'Countdown Cards',
                'db_table': 'countdown_cards',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ImagePost',
            fields=[
                ('id', models.CharField(default=core.models.generate_uuid, max_length=36, primary_key=True, serialize=False)),
                ('title', models.TextField()),
                ('description', models.TextField(blank=True, null=True)),
                ('category', models.CharField(choices=[('critical', 'Critical'), ('important', 'Important'), ('entertainment', 'Entertainment'), ('additional', 'Additional')], default='important', max_length=50)),
                ('cloudinary_public_id', models.TextField(blank=True, null=True)),
                ('cloudinary_url', models.TextField()),
                ('cloudinary_format', models.CharField(blank=True, max_length=50, null=True)),
                ('target_url', models.TextField(blank=True, null=True)),
                ('display_order', models.IntegerField(default=0)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('expired', 'Expired'), ('cancelled', 'Cancelled')], default='active', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('version', models.IntegerField(default=1)),
            ],
            options={
                'verbose_name': 'Image Post',
                'verbose_name_plural': 'Image Posts',
                'db_table': 'image_posts',
                'ordering': ['display_order', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('item_name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('category', models.CharField(choices=[('lost', 'Lost'), ('found', 'Found'), ('claimed', 'Claimed'), ('unclaimed', 'Unclaimed')], default='lost', max_length=50)),
                ('location', models.CharField(blank=True, max_length=255, null=True)),
                ('date_found', models.DateTimeField(blank=True, null=True)),
                ('image_url', models.TextField(blank=True, null=True)),
                ('contact_info', models.CharField(blank=True, max_length=255, null=True)),
                ('reported_by', models.IntegerField(blank=True, null=True)),
                ('claimed_by', models.IntegerField(blank=True, null=True)),
                ('claimed_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(default='open', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'properties',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RegistrationFormField',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('field_name', models.CharField(max_length=100)),
                ('field_key', models.CharField(help_text='Unique identifier for the field (e.g., full_name, email)', max_length=100)),
                ('field_type', models.CharField(choices=[('text', 'Text'), ('email', 'Email'), ('number', 'Number'), ('date', 'Date'), ('select', 'Select/Dropdown'), ('textarea', 'Text Area'), ('tel', 'Phone Number')], default='text', max_length=20)),
                ('field_label', models.CharField(max_length=255)),
                ('placeholder', models.CharField(blank=True, max_length=255, null=True)),
                ('options', models.TextField(blank=True, help_text='JSON array for select options', null=True)),
                ('is_required', models.BooleanField(default=False)),
                ('display_order', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'registration_form_fields',
                'ordering': ['display_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='SystemSetting',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('setting_key', models.CharField(max_length=100, unique=True)),
                ('setting_value', models.TextField(blank=True, null=True)),
                ('setting_type', models.CharField(choices=[('string', 'String'), ('integer', 'Integer'), ('boolean', 'Boolean'), ('json', 'JSON')], default='string', max_length=20)),
                ('description', models.TextField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'system_settings',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('uuid', models.CharField(default=core.models.generate_uuid, max_length=36, unique=True)),
                ('full_name', models.CharField(max_length=255)),
                ('registration_number', models.CharField(max_length=100, unique=True)),
                ('email', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('phone', models.CharField(blank=True, max_length=50, null=True)),
                ('password_hash', models.CharField(blank=True, max_length=255, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_verified', models.BooleanField(default=False)),
                ('is_admin', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('active', 'Active'), ('flagged', 'Flagged'), ('inactive', 'Inactive'), ('banned', 'Banned')], default='active', max_length=20)),
                ('group_name', models.CharField(blank=True, max_length=100, null=True)),
                ('role', models.CharField(choices=[('member', 'Member'), ('admin', 'Admin'), ('moderator', 'Moderator')], default='member', max_length=50)),
                ('case_info', models.TextField(blank=True, null=True)),
                ('flagged_reason', models.TextField(blank=True, null=True)),
                ('flagged_by', models.IntegerField(blank=True, null=True)),
                ('flagged_at', models.DateTimeField(blank=True, null=True)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('login_count', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'users',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UserGroup',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('group_name', models.CharField(max_length=100, unique=True)),
                ('group_code', models.CharField(blank=True, max_length=20, null=True, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('max_members', models.IntegerField(default=50)),
                ('current_members', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('is_flagged', models.BooleanField(default=False)),
                ('flagged_reason', models.TextField(blank=True, null=True)),
                ('leader_id', models.IntegerField(blank=True, null=True)),
                ('created_by', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'user_groups',
                'ordering': ['group_name'],
            },
        ),
        migrations.CreateModel(
            name='UserGroupMember',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('user_id', models.IntegerField()),
                ('group_id', models.IntegerField()),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('is_leader', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('active', 'Active'), ('pending', 'Pending'), ('removed', 'Removed')], default='active', max_length=20)),
            ],
            options={
                'db_table': 'user_group_members',
                'unique_together': {('user_id', 'group_id')},
            },
        ),
        migrations.DeleteModel(
            name='SliderImage',
        ),
    ]
