# Generated by Django 4.2.11 on 2026-03-31 18:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_countdowncard_imagepost_property_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExternalTable',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('table_name', models.CharField(max_length=100, unique=True)),
                ('fields_schema', models.TextField()),
                ('record_count', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'external_tables',
            },
        ),
        migrations.CreateModel(
            name='ExternalTableRecord',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('data', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('table', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='records', to='core.externaltable')),
            ],
            options={
                'db_table': 'external_table_records',
            },
        ),
    ]
