# Generated by Django 4.2.11 on 2026-04-02 00:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_externaltable_externaltablerecord'),
    ]

    operations = [
        migrations.AddField(
            model_name='externaltable',
            name='is_visible',
            field=models.BooleanField(default=True),
        ),
    ]
