# Generated by Django 4.2.11 on 2026-04-03 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_externaltable_is_visible'),
    ]

    operations = [
        migrations.AddField(
            model_name='externaltable',
            name='hidden_columns',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
