# Generated by Django 6.0.3 on 2026-04-08 00:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_externaltable_hidden_columns'),
    ]

    operations = [
        migrations.AlterField(
            model_name='externaltable',
            name='fields_schema',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='externaltablerecord',
            name='data',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
