# Generated by Django 6.0.3 on 2026-04-08 00:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_upgrade_external_tables_json'),
    ]

    operations = [
        migrations.AlterField(
            model_name='externaltable',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='externaltable',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AlterField(
            model_name='externaltable',
            name='is_visible',
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AlterField(
            model_name='externaltable',
            name='table_name',
            field=models.CharField(db_index=True, max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='externaltablerecord',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AddIndex(
            model_name='externaltablerecord',
            index=models.Index(fields=['table', '-created_at'], name='external_ta_table_i_622227_idx'),
        ),
    ]
