# Generated by Django 6.0.3 on 2026-04-08 01:00

import django.contrib.postgres.indexes
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_add_performance_indexes'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='externaltablerecord',
            index=django.contrib.postgres.indexes.GinIndex(fields=['data'], name='external_ta_data_b69208_gin'),
        ),
    ]
