# Generated by Django 4.2.11 on 2026-04-12 00:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_add_gin_json_index'),
    ]

    operations = [
        migrations.AddField(
            model_name='imagepost',
            name='created_by',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
