# Generated by Django 4.2.11 on 2026-04-12 00:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_imagepost_created_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='externaltable',
            name='created_by',
            field=models.IntegerField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='created_by',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='systemsetting',
            name='created_by',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
