# Generated by Django 4.2.11 on 2026-04-12 00:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_externaltable_created_by_property_created_by_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='systemsetting',
            name='setting_key',
            field=models.CharField(max_length=100),
        ),
        migrations.AddConstraint(
            model_name='systemsetting',
            constraint=models.UniqueConstraint(fields=('setting_key', 'created_by'), name='uniq_setting_per_owner'),
        ),
    ]
