# Generated by Django 4.2.11 on 2026-04-12 00:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_alter_systemsetting_setting_key_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='registrationformfield',
            name='created_by',
            field=models.IntegerField(blank=True, db_index=True, null=True),
        ),
    ]
