# Generated by Django 6.0.3 on 2026-04-09 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0002_alter_crtenant_schema_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenantsubscription',
            name='status',
            field=models.CharField(choices=[('trial', 'Trial'), ('active', 'Active'), ('grace_period', 'Grace Period'), ('past_due', 'Past Due'), ('suspended', 'Suspended'), ('cancelled', 'Cancelled')], default='trial', max_length=20),
        ),
        migrations.AlterField(
            model_name='tenantsubscription',
            name='plan',
            field=models.CharField(choices=[('trial', 'Trial'), ('basic', 'Basic'), ('pro', 'Pro')], default='trial', max_length=20),
        ),
    ]
